### PR TITLE
Exercise 4

### PR DESCRIPTION
**Pull request by n4g0r**
Frederic Gaillard
Epraim Schott

### CODE REVIEW

**Comment by Tidebreaker** [comment]
App looks o.k., milf-jokes are unnecessary. I can't open you app after installing it. 7/10 for now

**Comment by n4g0r** [comment]
We removed the intent filter on purpose as the app opens when a tag is
scanned. App is quite useless otherwise.
Grüße

2015-06-18 21:08 GMT+02:00 Johannes <notifications@github.com>:

**Comment by Tidebreaker** [comment]
That's fine but I somehow can't seem to trigger it with scanning a tag either?

**Comment by n4g0r** [comment]
The nfc tag at B11 and e.g. thoska worked perfectly on my n5 (5.1.1). Would
a Screenshot help?
Am 18.06.2015 9:54 nachm. schrieb "Johannes" <notifications@github.com>:
>
> That's fine but I somehow can't seem to trigger it with scanning a tag
either?

**Pull request closed without merging**
